### PR TITLE
feature/handiccaped_inc/design_patterns

### PR DESCRIPTION
**Pull request by SantiAV25**
Authors:  Santiago Agredo Vallejo <sagredov@unicauca.edu.co>
              Pablo Jose Restrepo Ruiz <prestrepo@unicauca.edu.co>
              Jojan Esteban  Serna Serna <jeserna@unicauca.edu.co>
              Arturo Restrepo Ruiz <arturorr@unicauca.edu.co>

### CODE REVIEW

**Comment by Jojan-Esteban-Serna** [comment]
LGTM

**Review by Jojan-Esteban-Serna — APPROVED** [review]
LGTM

**Review by Pablo-Restrepo — APPROVED** [review]
LGTM

**Comment by zahydo** [comment]
Well done

**Review by zahydo — APPROVED** [review]
👍

**Pull request merged**
